In [3]:
import tensorflow as tf

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [8]:
x = tf.Variable(4.0)
with tf.GradientTape() as tape:
    y = x**2
dy_dx = tape.gradient(y, x)
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [6]:
# Define a simple model
model = tf.keras.Sequential([tf.keras.layers.Dense(1)])
optimizer = tf.optimizers.SGD(learning_rate=0.01)

# Sample data
x = tf.constant([[2.0]])  # Input
y_true = tf.constant([[5.0]])  # Target output

# Forward pass and backpropagation with GradientTape
with tf.GradientTape() as tape:
    y_pred = model(x)  # Model prediction
    loss = tf.losses.mse(y_true, y_pred)  # Compute loss

# Compute gradients and apply them
gradients = tape.gradient(loss, model.trainable_variables)  # Compute gradients
print(gradients)
optimizer.apply_gradients(zip(gradients, model.trainable_variables))  # Update parameters


[<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-27.697845]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-13.848923], dtype=float32)>]


<KerasVariable shape=(), dtype=int64, path=SGD/iteration>